
name: 'Red Hat Helm Chart Certifier'
description: ''
inputs:
  chart_uri:
    description: URI to Helm Chart to verify. This can be a path to the chart directory, or an http(s) URI.
    required: true
  report_type:
    description: '{all,annotations,digests,metadata,results}'
    required: true
    default: results
  profile_name:
    description: Chart checks profile to run. See https://github.com/redhat-certification/chart-verifier/tree/main/config for a list of profiles.
    required: false
  profile_version:
    description: Version of profile_name to run. If profile_name is set but profile_version is not, the latest version is used.
    required: false
  verify_args:
    description: Extra arguments to pass to the 'verify' command. See 'chart-verifier verify --help' for more info.
    required: false
  fail:
    description: If true, exit with code 1 if at least one check is failed. Else, always exit with code 0 - ie, never fail the workflow step.
    required: false
    default: 'true'
# outputs:

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CHART_URI: ${{ inputs.chart_uri }}
    REPORT_TYPE: ${{ inputs.report_type }}
    PROFILE_NAME: ${{ inputs.profile_name }}
    PROFILE_VERSION: ${{ inputs.profile_version }}
    FAIL: ${{ inputs.fail }}
  args:
    - ${{ inputs.verify_args }}
